---
services:
  nginx:
    image: nginx:1.23.3
    ports:
      - 8080:80
    configs:
      - source: nginx-config
        target: /etc/nginx/conf.d/default.conf
    volumes:
      - type: bind
        source: $LANDISK_MOUNT_POINT
        target: /usr/share/nginx/html
        read_only: true
    restart: unless-stopped
configs:
  nginx-config:
    file: ./default.conf
